### ISSUE TITLE
Final Capstone App Group and Setup

### ISSUE THREAD

**Issue by leonardodiasb** [leonardodiasb/final-capstone-back-end#20]
In this activity, our team prepared a Kanban board with a GitHub project. This time there is not template to copy. We create a Kanban board from scratch. Project requirements are separate tasks and they have a card for each task.

## Links

- [Kanban](https://github.com/leonardodiasb/final-capstone-back-end/projects/1).
- [Requirements](https://github.com/microverseinc/curriculum-final-capstone/blob/main/projects/business_requirements.md).

## Group

- Leonardo Dias.
- Daniel Jaramilo.
- Alonso Falconi.
- Abimbola Buari.

## Screenshots

![ss1](https://user-images.githubusercontent.com/61919617/144316523-07352105-af38-401a-a58a-744b5eb33907.png)
![ss2](https://user-images.githubusercontent.com/61919617/144316533-2784325d-21d8-43c9-a69b-a53590f8e24a.png)

**Comment by MuriloRoque** [comment]
Hi @leonardodiasb, @bimbolabuari, @D4nielJ, @alonsofl, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your project.

## Invalid Code Review Request

You have submitted a project, that doesn't have the following requirement:

- [ ] Take a screenshot of your board and add it to your issue's description (do it before each review to always have the freshest version of your board). You will need it for the final evaluation.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the issue thread if something is not 100% clear.

**_Please, do not open a new Issue for re-reviews. You should use the same Issue submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by MuriloRoque** [comment]
Hi @leonardodiasb, @bimbolabuari, @D4nielJ, @alonsofl, 

In my opinion, your project is ready!  There is nothing else to say other than... it's time to start it :shipit: 


Good luck! 🎉 


Feel free to leave any questions or comments in the issue thread if something is not 100% clear.
